name: nrc_prefix_finder
description: NRC Prefix Finder
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-164.0.dev

dependencies:
  http: ^1.1.0
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
